repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    - id: black
      language_version: python3.12

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      name: flake8
      types: [python]
      args:
      - --max-line-length=88
      - --ignore=E203,E501,W503,W291